name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Check build configuration
      run: npm run build -- --dry-run
      if: matrix.os != 'windows-latest'

  build:
    needs: test
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build for macOS
      if: matrix.os == 'macos-latest'
      run: npm run dist
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false
    
    - name: Build for Linux
      if: matrix.os == 'ubuntu-latest'
      run: npm run dist -- --linux
    
    - name: Build for Windows
      if: matrix.os == 'windows-latest'
      run: npm run dist -- --win
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: hexbloop-${{ matrix.os }}
        path: dist/*
        retention-days: 7