name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Build for macOS
      if: matrix.os == 'macos-latest'
      run: npm run dist
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false
    
    - name: Build for Linux
      if: matrix.os == 'ubuntu-latest'
      run: npm run dist -- --linux
    
    - name: Build for Windows
      if: matrix.os == 'windows-latest'
      run: npm run dist -- --win
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}